package com.github.artamonovkirill.pact

import au.com.dius.pact.provider.junit.PactRunner
import au.com.dius.pact.provider.junit.Provider
import au.com.dius.pact.provider.junit.loader.PactFolder
import au.com.dius.pact.provider.junit.target.HttpTarget
import au.com.dius.pact.provider.junit.target.Target
import au.com.dius.pact.provider.junit.target.TestTarget
import com.github.tomakehurst.wiremock.WireMockServer
import groovy.json.JsonOutput
import org.junit.After
import org.junit.Before
import org.junit.runner.RunWith

import static com.github.tomakehurst.wiremock.client.WireMock.*
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig

@RunWith(PactRunner)
@Provider('Provider')
@PactFolder('target/pacts')
class ProviderTest {

    def config = wireMockConfig()
            .port(9000)
    def wiremock = new WireMockServer(config)

    /* used by autogenerated test classes */
    @SuppressWarnings('GroovyUnusedDeclaration')
    @TestTarget
    public static Target target = new HttpTarget('localhost', 9000)

    @Before
    void 'Start wiremock'() {
        wiremock.start()
        wiremock.stubFor(get(urlEqualTo(ConsumerSpec.PATH))
                .willReturn(aResponse()
                .withStatus(200)
                .withHeader('Content-Type', 'application/json')
                .withBody(JsonOutput.toJson(ConsumerSpec.BODY))))
    }

    @After
    void 'Stop wiremock'() {
        wiremock.stop()
    }

}
