package com.github.artamonovkirill.pact.nested

import au.com.dius.pact.provider.junit.PactRunner
import au.com.dius.pact.provider.junit.Provider
import au.com.dius.pact.provider.junit.loader.PactFolder
import au.com.dius.pact.provider.junit.target.HttpTarget
import au.com.dius.pact.provider.junit.target.Target
import au.com.dius.pact.provider.junit.target.TestTarget
import com.github.tomakehurst.wiremock.WireMockServer
import org.junit.After
import org.junit.Before
import org.junit.runner.RunWith

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse
import static com.github.tomakehurst.wiremock.client.WireMock.get
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo

@RunWith(PactRunner)
@Provider('NestedProvider')
@PactFolder('target/pacts')
class NestedEqualsProviderTest {

    def wiremock = new WireMockServer(NestedEqualsConsumerSpec.PORT)

    /* used by autogenerated test classes */
    @SuppressWarnings('GroovyUnusedDeclaration')
    @TestTarget
    public static Target target = new HttpTarget(
            'localhost',
            NestedEqualsConsumerSpec.PORT)

    @Before
    void 'Start wiremock'() {
        wiremock.start()
        wiremock.stubFor(get(urlEqualTo(NestedEqualsConsumerSpec.PATH))
                .willReturn(aResponse()
                .withStatus(200)
                .withHeader('Content-Type', 'application/json')
                .withBody('''{
                                    "flag": true,
                                    "str": "1",
                                    "arr": [
                                      {
                                        "flag": false,
                                        "str": ""
                                      }
                                    ]                               
                                  }''')))
    }

    @After
    void 'Stop wiremock'() {
        wiremock.stop()
    }

}
